image_width: 1280
image_height: 1024
camera_name: camera_hik
camera_matrix:
  rows: 3
  cols: 3
  data: [600.0, 0.0, 320.0, 0.0, 600.0, 240.0, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.05, 0.01, -0.001, 0.001, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [600.0, 0.0, 320.0, 0.0,
         0.0, 600.0, 240.0, 0.0,
         0.0, 0.0, 1.0, 0.0]